### ISSUE TITLE
Problem z systemem nicków

### ISSUE THREAD

**Issue by Myszka30** [Myszka30/modpack-mc-klasowy#1]
Gdy odpalisz kilka razy instalator w pliku`username.txt` gromadzą się nazwy w kolejnych linijkach!
[image-1.png](https://github.com/Myszka30/modpack-mc-klasowy/assets/87234858/62b81afe-bc0c-4ce7-96df-ee1a22137ec1)

**Comment by Bbolken1q** [comment]
![image](https://github.com/Myszka30/modpack-mc-klasowy/assets/122157883/620d79d7-2fe3-4022-955f-c24121965c0e)

**Comment by Myszka30** [comment]
na uh
